#master del sql (las relaciones entre las tablas en lenguaje sql)
SE [Estudiante]
GO
/****** Object:  Database [Estudiante]    Script Date: 24-04-2025 10:12:47 ******/

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Estudiante].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Estudiante] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Estudiante] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Estudiante] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Estudiante] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Estudiante] SET ARITHABORT OFF 
GO
ALTER DATABASE [Estudiante] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Estudiante] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Estudiante] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Estudiante] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Estudiante] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Estudiante] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Estudiante] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Estudiante] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Estudiante] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Estudiante] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Estudiante] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Estudiante] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Estudiante] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Estudiante] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Estudiante] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Estudiante] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Estudiante] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Estudiante] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Estudiante] SET  MULTI_USER 
GO
ALTER DATABASE [Estudiante] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Estudiante] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Estudiante] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Estudiante] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Estudiante] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Estudiante] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Estudiante] SET QUERY_STORE = ON
GO
ALTER DATABASE [Estudiante] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Estudiante]
GO
/****** Object:  Table [dbo].[Ciudad]    Script Date: 24-04-2025 10:12:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ciudad](
	[id_ciudad] [int] NOT NULL,
	[nombre_ciudad] [nchar](50) NOT NULL,
 CONSTRAINT [PK_Ciudad] PRIMARY KEY CLUSTERED 
(
	[id_ciudad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estado_Civil]    Script Date: 24-04-2025 10:12:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estado_Civil](
	[id_estado_civil] [tinyint] NOT NULL,
	[nombre_estado_civil] [nchar](50) NOT NULL,
 CONSTRAINT [PK_Estado_Civil] PRIMARY KEY CLUSTERED 
(
	[id_estado_civil] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estudiante]    Script Date: 24-04-2025 10:12:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estudiante](
	[rut_estudiante] [nchar](10) NOT NULL,
	[nombre_estudiante] [nchar](100) NOT NULL,
	[id_estado_civil] [tinyint] NOT NULL,
	[id_ciudad] [int] NOT NULL,
 CONSTRAINT [PK_Estudiante] PRIMARY KEY CLUSTERED 
(
	[rut_estudiante] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Estudiante]  WITH CHECK ADD  CONSTRAINT [FK_Estudiante_Ciudad] FOREIGN KEY([id_ciudad])
REFERENCES [dbo].[Ciudad] ([id_ciudad])
GO
ALTER TABLE [dbo].[Estudiante] CHECK CONSTRAINT [FK_Estudiante_Ciudad]
GO
ALTER TABLE [dbo].[Estudiante]  WITH CHECK ADD  CONSTRAINT [FK_Estudiante_Estado_Civil] FOREIGN KEY([id_estado_civil])
REFERENCES [dbo].[Estado_Civil] ([id_estado_civil])
GO
ALTER TABLE [dbo].[Estudiante] CHECK CONSTRAINT [FK_Estudiante_Estado_Civil]
GO
USE [master]
GO
ALTER DATABASE [Estudiante] SET  READ_WRITE 
GO
